add_lunch_combo angler-userdebug
add_lunch_combo bullhead-userdebug
add_lunch_combo dragon-userdebug
add_lunch_combo marlin-userdebug
add_lunch_combo sailfish-userdebug
add_lunch_combo shamu-userdebug
